### ISSUE TITLE
Exception when no devices available

### ISSUE THREAD

**Issue by marcdjulien** [marcdjulien/spotifyterminal#27]
```
Traceback (most recent call last):
  File "./spotify.py", line 58, in <module>
    display.start()
  File "/home/mjulien2/spotifyterminal/display.py", line 118, in start
    self.render()
  File "/home/mjulien2/spotifyterminal/display.py", line 180, in render
    self.render_footer()
  File "/home/mjulien2/spotifyterminal/display.py", line 277, in render_footer
    text = self.state.current_menu.get_current_list_entry().str(self._cols)
AttributeError: 'NoneType' object has no attribute 'str'
```

**Comment by marcdjulien** [comment]
Fixed on cc71261.
