### ISSUE TITLE
First run after installation fails with error "'Thread' object has no attribute 'isAlive'"

### ISSUE THREAD

**Issue by phunanon** [marcdjulien/spotifyterminal#89]
I installed with `pip install spotify-terminal` on my Raspberry Pi `Linux raspberrypi 5.10.92+ #1514 Mon Jan 17 17:35:21 GMT 2022 armv6l GNU/Linux`  
Python 3.9.2, pip 20.3.4  
I then closed and reopened my terminal and ran `spotify-terminal.py -u xxxxx` (user ID) and received this output:

```
... ASCII art ...
   v0.15.3

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/.local/lib/python3.9/site-packages/spotify_terminal/authentication.py", line 67, in show_link
    if web_thread.isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'
```

**Comment by marcdjulien** [comment]
A fix for this was recently merged:
https://github.com/marcdjulien/spotify-terminal/pull/88

I'll deploy it to pypi  later today.

**Comment by ghost** [comment]
second run throws a segfault (pip, windows 11)

![image](https://user-images.githubusercontent.com/64506392/177059215-2d559288-637c-4188-a2be-5e288bb04f96.png)
